[package]
name = "installer"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
simplelog = "0.12.1"
clap = "4.4.11"
toml = "0.8.8"
serde = { version = "1.0.193", features = ["derive"] }