on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - name: Linux
            extension: ''
            platform: x86_64-unknown-linux-gnu
          - name: Windows
            extension: .exe
            platform: x86_64-pc-windows-gnu
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - name: Build project
        run: |
          rustup target add ${{ matrix.target.platform }}
          cargo build --release --target ${{ matrix.target.platform }}
      - name: Copy files
        run: >
          mv target/${{ matrix.target.platform }}/release/installer${{
          matrix.target.extension }} installer${{ matrix.target.extension }}
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: '${{ matrix.target.name | lower() }}'
          path: 'installer${{ matrix.target.extension }}'
