on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: linux
            extension: ''
            platform: x86_64-unknown-linux-gnu
          - name: windows
            extension: .exe
            platform: x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install MinGW
        if: matrix.target.platform == 'x86_64-pc-windows-gnu'
        run: sudo apt install -y gcc-mingw-w64-x86-64
      - name: Build project
        run: |
          rustup target add ${{ matrix.target.platform }}
          cargo build --release --target ${{ matrix.target.platform }}
      - name: Copy files
        run: |
          mv target/${{ matrix.target.platform }}/release/installer${{matrix.target.extension }} installer${{ matrix.target.extension }}
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: '${{ matrix.target.name }}'
          path: 'installer${{ matrix.target.extension }}'